// Mood presets. Each is a starting point tuned by ear-logic; the composer reads them as
// probabilities and ranges, never as fixed patterns.
//
// lead / second      weighted instrument choice for the melody and for call-and-response
//                    ('other' = whichever of xiao/zheng is not leading, 'harm' = qin harmonics)
// echo               chance a phrase tail is echoed by the second instrument
// counter            { inst, p }: sustained countermelody per phrase
// rhythm, density    rhythm-cell vocabulary and how many notes per cell
// ornament           multiplier on grace notes, slides, falls
// bars, breath       phrase lengths in bars; rest beats closing each phrase
// arp, arpRate       chance of zheng broken chords per phrase, notes per beat (2 = 8ths, 4 = 16ths)
// bass, qinBass      zheng open fifths on strong beats; low qin notes (qinPizz: short plucked bass)
// harmonics, muyu    qin harmonic in the phrase breath; woodblock offbeats
// glissSection/Phrase zheng glissando pickups; tremolo: 摇指 on climax notes; staccato: damped short notes
// harmonicPhrase     qin lead plays a whole phrase in harmonics (泛音段)
// modeShift          chance a section moves to a sibling mode over the same five pitches
// interlude          weights of interlude types; interludeSec: duration range
// leadCenter         optional MIDI centre per lead instrument (keeps the tune above arpeggios)
// transition         weights of the gesture that opens this mood after setMood()
// reverb, wet, gain  send scale, return level, master trim

export const PRESETS = {
  moonrise: {
    title: '海上生明月',
    tonic: 'B',
    mode: 'yu',
    bpm: 52,
    lead: { xiao: 1 },
    second: { zheng: 1, harm: 0.4 },
    echo: 0.45,
    counter: null,
    rhythm: 'slow',
    density: 0.5,
    ornament: 1,
    bars: [2, 3, 3, 4],
    breath: [2, 3, 4],
    arp: 0.4,
    arpRate: [2],
    arpShapes: ['rolling', 'open', 'rise'],
    arpVel: 0.9,
    bass: 0.25,
    qinBass: 0.45,
    harmonics: 0.3,
    muyu: 0,
    glissSection: 0.3,
    glissPhrase: 0,
    tremolo: 0,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.15,
    siblings: ['gong', 'shang'],
    interlude: { harmonics: 2, zhengArp: 1.5, silence: 1.5, qin: 0.5 },
    interludeSec: [8, 18],
    transition: { gliss: 1, harmonic: 1.5 },
    reverb: 1.35,
    wet: 1.15,
    gain: 1.26,
  },
  wall: {
    title: '长城',
    tonic: 'A',
    mode: 'zhi',
    bpm: 58,
    lead: { qin: 1 },
    second: { xiao: 1 },
    echo: 0.3,
    counter: { inst: 'xiao', p: 0.35 },
    rhythm: 'slow',
    density: 0.6,
    ornament: 1,
    bars: [2, 3, 3, 4],
    breath: [2, 3, 4],
    arp: 0.15,
    arpRate: [2],
    arpShapes: ['open'],
    arpVel: 0.85,
    bass: 0.65,
    qinBass: 0,
    harmonics: 0.2,
    muyu: 0,
    glissSection: 0.35,
    glissPhrase: 0,
    tremolo: 0,
    staccato: 0,
    harmonicPhrase: 0.15,
    modeShift: 0.15,
    siblings: ['shang', 'gong'],
    interlude: { qin: 1.5, harmonics: 1, silence: 1, zhengArp: 0.5 },
    interludeSec: [7, 16],
    transition: { gliss: 1.2, harmonic: 1 },
    reverb: 1.1,
    wet: 1,
    gain: 2.21,
  },
  voyage: {
    title: '1784 远航',
    tonic: 'E',
    mode: 'shang',
    bpm: 76,
    lead: { zheng: 1 },
    leadCenter: { zheng: 74 },
    second: { xiao: 1 },
    echo: 0.25,
    counter: { inst: 'xiao', p: 0.65 },
    rhythm: 'fast',
    density: 1,
    ornament: 0.8,
    bars: [3, 4, 4],
    breath: [2, 3],
    arp: 0.85,
    arpRate: [4],
    arpShapes: ['wave', 'rolling'],
    arpVel: 0.85,
    bass: 0.55,
    qinBass: 0.25,
    harmonics: 0.1,
    muyu: 0,
    glissSection: 0.6,
    glissPhrase: 0.15,
    tremolo: 0.8,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.15,
    siblings: ['yu', 'zhi'],
    interlude: { zhengArp: 2, harmonics: 0.6, silence: 0.5 },
    interludeSec: [5, 12],
    transition: { gliss: 2, harmonic: 0.5 },
    reverb: 0.9,
    wet: 0.9,
    gain: 1.9,
  },
  bridge: {
    title: '长桥卧波',
    tonic: 'D',
    mode: 'gong',
    bpm: 66,
    lead: { xiao: 1, zheng: 1 },
    second: { other: 1 },
    echo: 0.8,
    counter: null,
    rhythm: 'medium',
    density: 0.8,
    ornament: 1,
    bars: [2, 3, 4],
    breath: [2, 3, 4],
    arp: 0.5,
    arpRate: [2],
    arpShapes: ['rolling', 'rise', 'open'],
    arpVel: 0.9,
    bass: 0.4,
    qinBass: 0.2,
    harmonics: 0.2,
    muyu: 0,
    glissSection: 0.4,
    glissPhrase: 0,
    tremolo: 0.3,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.2,
    siblings: ['yu', 'zhi'],
    interlude: { zhengArp: 1.5, harmonics: 1, silence: 1 },
    interludeSec: [6, 14],
    transition: { gliss: 1.5, harmonic: 1 },
    reverb: 1.05,
    wet: 1,
    gain: 1.74,
  },
  panda: {
    title: '熊猫',
    tonic: 'G',
    mode: 'gong',
    bpm: 88,
    lead: { zheng: 1 },
    leadCenter: { zheng: 74 },
    second: { zheng: 0.6, xiao: 0.4 },
    echo: 0.45,
    counter: null,
    rhythm: 'fast',
    density: 1.05,
    ornament: 0.8,
    bars: [2, 2, 3],
    breath: [2],
    arp: 0.3,
    arpRate: [2],
    arpShapes: ['open', 'rise'],
    arpVel: 0.8,
    bass: 0.3,
    qinBass: 0.75,
    qinPizz: true,
    harmonics: 0.15,
    muyu: 0.35,
    glissSection: 0.35,
    glissPhrase: 0,
    tremolo: 0.2,
    staccato: 0.55,
    harmonicPhrase: 0,
    modeShift: 0.1,
    siblings: ['zhi'],
    interlude: { zhengArp: 1, harmonics: 1, silence: 0.6 },
    interludeSec: [5, 10],
    transition: { gliss: 1.5, harmonic: 1 },
    reverb: 0.75,
    wet: 0.85,
    gain: 2.29,
  },
  garden: {
    title: '玫瑰与牡丹',
    tonic: 'G',
    mode: 'gong',
    bpm: 60,
    lead: { zheng: 1 },
    second: { xiao: 1 },
    echo: 0.35,
    counter: { inst: 'xiao', p: 0.6 },
    rhythm: 'medium',
    density: 0.7,
    ornament: 1.1,
    bars: [2, 3, 4],
    breath: [2, 3, 4],
    arp: 0.55,
    arpRate: [2],
    arpShapes: ['rolling', 'rise'],
    arpVel: 0.85,
    bass: 0.3,
    qinBass: 0.15,
    harmonics: 0.2,
    muyu: 0,
    glissSection: 0.3,
    glissPhrase: 0,
    tremolo: 0.4,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.35,
    siblings: ['yu'],
    interlude: { zhengArp: 1.5, harmonics: 1, silence: 1 },
    interludeSec: [6, 15],
    transition: { gliss: 1, harmonic: 1 },
    reverb: 1.05,
    wet: 1,
    gain: 2.13,
  },
  finale: {
    title: '天涯若比邻',
    tonic: 'D',
    mode: 'gong',
    bpm: 63,
    lead: { xiao: 1 },
    second: { zheng: 1 },
    echo: 0.4,
    counter: null,
    rhythm: 'medium',
    density: 0.8,
    ornament: 1,
    bars: [3, 4],
    breath: [2, 3],
    arp: 0.9,
    arpRate: [2, 4],
    arpShapes: ['rolling', 'wave', 'rise'],
    arpVel: 0.85,
    bass: 0.7,
    qinBass: 0.6,
    harmonics: 0.25,
    muyu: 0,
    glissSection: 0.8,
    glissPhrase: 0.55,
    tremolo: 0,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.15,
    siblings: ['yu', 'zhi'],
    interlude: { zhengArp: 1.5, harmonics: 1.2, silence: 0.5 },
    interludeSec: [5, 12],
    transition: { gliss: 2, harmonic: 1 },
    reverb: 1.05,
    wet: 1,
    gain: 1.36,
  },
  pine: {
    title: '松鹤',
    tonic: 'A',
    mode: 'zhi',
    bpm: 56,
    lead: { qin: 1 },
    second: { harm: 1 },
    echo: 0.35,
    counter: null,
    rhythm: 'slow',
    density: 0.5,
    ornament: 1.1,
    bars: [2, 3, 3],
    breath: [2, 3, 4],
    arp: 0,
    arpRate: [2],
    arpShapes: ['open'],
    arpVel: 0.8,
    bass: 0,
    qinBass: 0.1,
    harmonics: 0.35,
    muyu: 0,
    glissSection: 0,
    glissPhrase: 0,
    tremolo: 0,
    staccato: 0,
    harmonicPhrase: 0.35,
    modeShift: 0.15,
    siblings: ['shang', 'gong'],
    interlude: { harmonics: 2, silence: 1.5, qin: 1.5 },
    interludeSec: [7, 16],
    transition: { harmonic: 2, gliss: 0.3 },
    reverb: 1.2,
    wet: 1.1,
    gain: 2.5,
  },
  plum: {
    title: '梅',
    tonic: 'E',
    mode: 'yu',
    bpm: 50,
    lead: { xiao: 1 },
    second: { zheng: 1, harm: 0.5 },
    echo: 0.25,
    counter: null,
    rhythm: 'slow',
    density: 0.4,
    ornament: 0.9,
    bars: [2, 3],
    breath: [3, 4],
    arp: 0.12,
    arpRate: [2],
    arpShapes: ['open'],
    arpVel: 0.8,
    bass: 0.1,
    qinBass: 0.2,
    harmonics: 0.3,
    muyu: 0,
    glissSection: 0.1,
    glissPhrase: 0,
    tremolo: 0,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.1,
    siblings: ['gong'],
    interlude: { silence: 2, harmonics: 1.5, zhengArp: 0.6 },
    interludeSec: [8, 20],
    transition: { harmonic: 1.5, gliss: 0.6 },
    reverb: 1.35,
    wet: 1.15,
    gain: 1.38,
  },
  river: {
    title: '江雪 · 渔舟',
    tonic: 'G',
    mode: 'zhi',
    bpm: 60,
    lead: { zheng: 1 },
    second: { xiao: 1 },
    echo: 0.35,
    counter: { inst: 'xiao', p: 0.25 },
    rhythm: 'medium',
    density: 0.7,
    ornament: 1.1,
    bars: [2, 3, 4],
    breath: [2, 3, 4],
    arp: 0.5,
    arpRate: [2],
    arpShapes: ['rolling', 'rise'],
    arpVel: 0.85,
    bass: 0.35,
    qinBass: 0.3,
    harmonics: 0.2,
    muyu: 0,
    glissSection: 0.3,
    glissPhrase: 0,
    tremolo: 0.35,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.15,
    siblings: ['shang', 'yu'],
    interlude: { zhengArp: 1.5, harmonics: 1, silence: 1, qin: 0.6 },
    interludeSec: [7, 16],
    transition: { gliss: 1.2, harmonic: 1 },
    reverb: 1.05,
    wet: 1,
    gain: 2.27,
  },
  bamboo: {
    title: '竹',
    tonic: 'G',
    mode: 'gong',
    bpm: 72,
    lead: { xiao: 1, zheng: 0.35 },
    leadCenter: { zheng: 74 },
    second: { zheng: 1 },
    echo: 0.35,
    counter: null,
    rhythm: 'medium',
    density: 0.85,
    ornament: 1,
    bars: [2, 3, 4],
    breath: [2, 3],
    arp: 0.75,
    arpRate: [4],
    arpShapes: ['wave', 'rise'],
    arpVel: 0.7,
    arpCenter: 57,
    bass: 0.2,
    qinBass: 0.1,
    harmonics: 0.2,
    muyu: 0,
    glissSection: 0.35,
    glissPhrase: 0,
    tremolo: 0.3,
    staccato: 0,
    harmonicPhrase: 0,
    modeShift: 0.2,
    siblings: ['yu', 'zhi'],
    interlude: { zhengArp: 1.5, harmonics: 1, silence: 0.8 },
    interludeSec: [5, 12],
    transition: { gliss: 1.3, harmonic: 1 },
    reverb: 0.95,
    wet: 0.95,
    gain: 1.67,
  },
};

export const MOOD_NAMES = Object.keys(PRESETS);
